Remove silent failures
djenriquez/replicator pull request #2
Opened 2019-06-05 21:58 UTC by djenriquez

Add debug logs to silent failures.

PTAL

2019-06-05 22:02 UTC, kainoaseto approved these changes
LGTM, these will still bubble up the actual error but this should help with confirming where it came from and for what group name

2019-06-05 22:04 UTC, kainoaseto commented
One thing before you merge though, left a comment in the files

2019-06-05 22:05 UTC, kainoaseto requested changes

2019-06-05 22:05 UTC, kainoaseto commented on client/job_scaling_policies.go
> +		logging.Debug("Failed to decode the groupMeta for %s", groupName)
We should add the groupMeta here for printOut since it's a pointer and could be off. It'd be useful to know the actual meta that failed to decode also

2019-06-05 22:05 UTC, djenriquez commented on client/job_scaling_policies.go
> +		logging.Debug("Failed to decode the groupMeta for %s", groupName)
How does one expand a map properly in a log?

2019-06-05 22:07 UTC, kainoaseto commented on client/job_scaling_policies.go
> +		logging.Debug("Failed to decode the groupMeta for %s", groupName)
You can just use a `%v` there's no quick and clean way to expand it with a loop that I know of

2019-06-05 22:09 UTC, kainoaseto commented on client/job_scaling_policies.go
> +		logging.Debug("Failed to decode the groupMeta for %s", groupName)
Apparently if it's json we can do this:
```
x := map[string]interface{}{"a": 1, "b": 2}
b, err := json.MarshalIndent(x, "", "  ")
if err != nil {
    fmt.Println("error:", err)
}
fmt.Print(string(b))
```

2019-06-08 04:36 UTC, zaquestion commented on client/job_scaling_policies.go
> +		logging.Debug("client/job_scaling_policies: Failed to create a decoder for %s", groupName)
consider logging the actual error as well. I'd suggest using https://github.com/pkg/errors, something like:
```
		logging.Debug(errors.Wrap(err, fmt.Sprintf("client/job_scaling_policies: Failed to create a decoder for %s", groupName)))
```

Same below.

2019-06-08 04:39 UTC, zaquestion commented on client/job_scaling_policies.go
> +		logging.Debug("Failed to decode the groupMeta for %s", groupName)
Consider using `spew` https://github.com/davecgh/go-spew, which is a bit more reliably/readable
e.g.
```
logging.Debug(... spew.Sdump(groupMeta))
```

2019-06-08 04:39 UTC, zaquestion approved these changes

2019-10-17 21:22 UTC, merged